# Generated by Django 3.0.2 on 2020-01-09 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load_models_conf',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('view_name', models.CharField(db_column='view_name', max_length=255)),
                ('model_index', models.CharField(db_column='model_index', max_length=255)),
                ('model_name', models.CharField(db_column='model_name', max_length=255)),
                ('model_url', models.CharField(db_column='model_url', max_length=255)),
                ('position_x', models.FloatField(db_column='position_x')),
                ('position_y', models.FloatField(db_column='position_y')),
                ('position_z', models.FloatField(db_column='position_z')),
                ('rotation_x', models.FloatField(db_column='rotation_x')),
                ('rotation_y', models.FloatField(db_column='rotation_y')),
                ('rotation_z', models.FloatField(db_column='rotation_z')),
                ('isdelete', models.BooleanField(db_column='f_is_delete', default=False)),
                ('createtime', models.DateTimeField(db_column='f_createtime', default=django.utils.timezone.now)),
                ('updatetime', models.DateTimeField(db_column='f_updatetime', default=django.utils.timezone.now)),
            ],
        ),
    ]
