# Generated by Django 3.0.2 on 2020-01-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load_models_conf',
            name='materials_color_b',
            field=models.FloatField(db_column='materials_color_b', default=0.13),
        ),
        migrations.AddField(
            model_name='load_models_conf',
            name='materials_color_g',
            field=models.FloatField(db_column='materials_color_g', default=0.13),
        ),
        migrations.AddField(
            model_name='load_models_conf',
            name='materials_color_r',
            field=models.FloatField(db_column='materials_color_r', default=0.13),
        ),
        migrations.AddField(
            model_name='load_models_conf',
            name='materials_type',
            field=models.IntegerField(db_column='materials_type', default=1),
        ),
    ]
