# Generated by Django 3.0.2 on 2020-01-28 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0004_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='com_model',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('model_name', models.CharField(db_column='model_name', max_length=255)),
                ('folder_id', models.IntegerField(db_column='folder_id', default=0)),
                ('url', models.CharField(db_column='url', max_length=255)),
                ('createtime', models.DateTimeField(db_column='f_createtime', default=django.utils.timezone.now)),
                ('isdelete', models.BooleanField(db_column='is_delete', default=False)),
            ],
        ),
    ]
