# Generated by Django 3.0.2 on 2020-02-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0005_com_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='load_models_conf',
            name='model_id',
            field=models.IntegerField(db_column='model_id', default=0),
        ),
    ]
