# Generated by Django 3.0.2 on 2020-02-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0007_auto_20200204_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='load_models_conf',
            name='serial',
            field=models.IntegerField(db_column='serial', default=0),
        ),
    ]
