# Generated by Django 3.0.2 on 2020-02-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0008_load_models_conf_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load_models_conf',
            name='model_name',
            field=models.CharField(db_column='model_name', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='load_models_conf',
            name='model_url',
            field=models.CharField(db_column='model_url', default='', max_length=255),
        ),
    ]
