# Generated by Django 3.0.2 on 2020-02-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0009_auto_20200204_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='load_models_conf',
            name='emissiveIntensity',
            field=models.FloatField(db_column='emissiveIntensity', default=0.1),
        ),
        migrations.AddField(
            model_name='load_models_conf',
            name='emissive_b',
            field=models.FloatField(db_column='emissive_b', default=1),
        ),
        migrations.AddField(
            model_name='load_models_conf',
            name='emissive_g',
            field=models.FloatField(db_column='emissive_g', default=1),
        ),
        migrations.AddField(
            model_name='load_models_conf',
            name='emissive_r',
            field=models.FloatField(db_column='emissive_r', default=1),
        ),
        migrations.AddField(
            model_name='load_models_conf',
            name='metalness',
            field=models.FloatField(db_column='metalness', default=1),
        ),
        migrations.AddField(
            model_name='load_models_conf',
            name='reflectivity',
            field=models.FloatField(db_column='reflectivity', default=0.5),
        ),
        migrations.AddField(
            model_name='load_models_conf',
            name='roughness',
            field=models.FloatField(db_column='roughness', default=0.5),
        ),
    ]
