# Generated by Django 3.0.2 on 2020-02-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0011_views_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='views',
            name='type',
        ),
        migrations.AddField(
            model_name='views',
            name='parent_id',
            field=models.IntegerField(db_column='parent_id', default=0),
        ),
    ]
