# Generated by Django 3.0.2 on 2020-02-08 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0012_auto_20200206_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='display_views',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('view_id', models.IntegerField(db_column='view_id', default=0)),
                ('display_name', models.CharField(db_column='display_name', max_length=255)),
                ('createtime', models.DateTimeField(db_column='createtime', default=django.utils.timezone.now)),
                ('isdelete', models.BooleanField(db_column='is_delete', default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='load_models_conf',
            name='emissiveIntensity',
            field=models.FloatField(db_column='emissiveIntensity', default=0),
        ),
    ]
