# Generated by Django 3.0.2 on 2020-02-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0013_auto_20200208_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='load_models_conf',
            name='view_position_x',
            field=models.FloatField(db_column='view_position_x', default=0),
        ),
        migrations.AddField(
            model_name='load_models_conf',
            name='view_position_y',
            field=models.FloatField(db_column='view_position_y', default=0),
        ),
        migrations.AddField(
            model_name='load_models_conf',
            name='view_position_z',
            field=models.FloatField(db_column='view_position_z', default=0),
        ),
    ]
