# Generated by Django 3.0.2 on 2020-02-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0015_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='owner_id',
            field=models.IntegerField(db_column='folder_id', default=1),
        ),
        migrations.AddField(
            model_name='views',
            name='owner_id',
            field=models.IntegerField(db_column='folder_id', default=1),
        ),
    ]
