# Generated by Django 3.0.3 on 2020-02-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0016_auto_20200216_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='type',
            field=models.IntegerField(db_column='type', default=1),
        ),
    ]
