# Generated by Django 3.0.3 on 2020-02-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0017_folder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='owner_id',
            field=models.IntegerField(db_column='owner_id', default=1),
        ),
    ]
