# Generated by Django 3.0.3 on 2020-02-24 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0019_auto_20200221_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='visit_log',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('page', models.IntegerField(db_column='page')),
                ('ip', models.CharField(db_column='ip', max_length=255)),
                ('createtime', models.DateTimeField(db_column='createtime', default=django.utils.timezone.now)),
            ],
        ),
    ]
