# Generated by Django 3.0.3 on 2020-02-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0020_visit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit_log',
            name='city',
            field=models.CharField(db_column='city', default='', max_length=255),
        ),
    ]
