# Generated by Django 3.0.3 on 2020-02-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0021_visit_log_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='load_models_conf',
            name='model_type',
            field=models.IntegerField(db_column='model_type', default=0),
        ),
    ]
